CREATE DATABASE IF NOT EXISTS COMERCIO;
USE COMERCIO;

CREATE TABLE CLIENTE(
    IDCLIENTE INT PRIMARY KEY AUTO_INCREMENT,
    NOME VARCHAR(30) NOT NULL,
    SEXO ENUM('M', 'F') NOT NULL,
    EMAIL VARCHAR(50) UNIQUE,
    CPF VARCHAR(15) UNIQUE
); 

CREATE TABLE ENDERECO(
    IDENDERECO INT PRIMARY KEY AUTO_INCREMENT,
    RUA VARCHAR(30) NOT NULL,
    BAIRRO VARCHAR(30) NOT NULL,
    CIDADE VARCHAR(30) NOT NULL,
    ESTADO CHAR(2) NOT NULL,

    ID_CLIENTE INT UNIQUE,
    FOREIGN KEY (ID_CLIENTE) REFERENCES CLIENTE(IDCLIENTE)
);

CREATE TABLE TELEFONE(
    IDTELEFONE INT PRIMARY KEY AUTO_INCREMENT,
    TIPO ENUM('Residencial', 'Comercial', 'Celular') NOT NULL,
    NUMERO VARCHAR(10) NOT NULL,

    ID_CLIENTE INT,
    FOREIGN KEY (ID_CLIENTE) REFERENCES CLIENTE(IDCLIENTE)
);

--INSERCAO NA TABELA CLIENTE
INSERT INTO CLIENTE VALUES(NULL, 'Joao', 'M', 'joao@gmail.com', '12345678910');
INSERT INTO CLIENTE VALUES(NULL, 'Maria', 'F', 'maria@gmail.com', '10987654321');
INSERT INTO CLIENTE VALUES(NULL, 'Jose', 'M', 'jose@gmail.com', '01597531234');
INSERT INTO CLIENTE VALUES(NULL, 'Rafael', 'M', 'rafael@gmail.com', '95135778945');
INSERT INTO CLIENTE VALUES(NULL, 'Alice', 'F', 'alice@gmail.com', '74185296336');
INSERT INTO CLIENTE VALUES(NULL, 'Clara', 'F', 'clara@gmail.com', '96385214710');


--INSERCAO NA TABELA ENDERECO
INSERT INTO ENDERECO VALUES(NULL, 'Avenida Gaspar Dutra', 'Jurujuba', 'Niteroi', 'RJ', 1);
INSERT INTO ENDERECO VALUES(NULL, 'Garbosa', 'Honorio Gurgel', 'Rio de Janeiro', 'RJ', 6);
INSERT INTO ENDERECO VALUES(NULL, 'Avenida Paulista', 'Bela Vista', 'Sao Paulo', 'SP', 2);
INSERT INTO ENDERECO VALUES(NULL, 'Ituna', 'Fidélis', 'Blumenau', 'SC', 5);
INSERT INTO ENDERECO VALUES(NULL, 'Avenida Afonso Pena', 'Boa Viagem', 'Belo Horizonte', 'MG ', 4);
INSERT INTO ENDERECO VALUES(NULL, 'Chile', 'Pelourinho', 'Salvador', 'BA', 3);


--INSERCAO NA TABELA TELEFONE
INSERT INTO TELEFONE VALUES(NULL, 'Residencial', '123456789', 2);
INSERT INTO TELEFONE VALUES(NULL, 'Comercial', '789456123', 1);
INSERT INTO TELEFONE VALUES(NULL, 'Residencial', '147852369', 4);
INSERT INTO TELEFONE VALUES(NULL, 'Residencial', '741258963', 4);
INSERT INTO TELEFONE VALUES(NULL, 'Celular', '753421967', 5);
INSERT INTO TELEFONE VALUES(NULL, 'Celular', '951623847', 3);
INSERT INTO TELEFONE VALUES(NULL, 'Comercial', '738694158', 6);
INSERT INTO TELEFONE VALUES(NULL, 'Celular', '914872635', 5);
INSERT INTO TELEFONE VALUES(NULL, 'Celular', '125418641', 2);